name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Configurar PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Instalar dependencias
    - name: Instalar dependencias
      run: composer install --prefer-dist --no-progress --no-suggest

    # Configurar la base de datos SQLite
    - name: Configurar base de datos
      run: |
        cp .env.example .env
        php artisan key:generate
        mkdir -p database
        touch database/database.sqlite

    # Ejecutar pruebas unitarias
    - name: Ejecutar pruebas
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
